spring.application.name=SB-EMS

#embeded tomcat port number
server.port=1234

#database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/emsdb
spring.datasource.username=root
spring.datasource.password=	1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#application properties
ems.save.success= SUCCESS : Employee Object Saved
ems.update.success= SUCESS : Employee Object Updated
ems.delete.success= SUCESS : Employee Object Deleted

#application error properties
ems.invalid.employee-details= FAILED : Invalid Employee Details
ems.invalid.employee-notfound= FAILED : Employee Not Found

ems.db.failed= FAILED : DB Error